include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
  
  errors:
    missing_required_param: error
    missing_return: error
    invalid_annotation_target: error
    deprecated_member_use: warning
    
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    # Error Prevention
    - avoid_empty_else
    - avoid_print
    - avoid_relative_lib_imports
    - avoid_types_as_parameter_names
    - cancel_subscriptions
    - close_sinks
    - no_duplicate_case_values
    - unrelated_type_equality_checks
    - valid_regexps
    
    # Style
    - always_declare_return_types
    - annotate_overrides
    - avoid_init_to_null
    - avoid_null_checks_in_equality_operators
    - avoid_return_types_on_setters
    - avoid_unnecessary_containers
    - camel_case_extensions
    - camel_case_types
    - constant_identifier_names
    - curly_braces_in_flow_control_structures
    - empty_catches
    - empty_constructor_bodies
    - file_names
    - library_names
    - library_prefixes
    - non_constant_identifier_names
    - prefer_adjacent_string_concatenation
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_contains
    - prefer_final_fields
    - prefer_for_elements_to_map_fromIterable
    - prefer_if_null_operators
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_single_quotes
    - prefer_spread_collections
    - sort_child_properties_last
    - unnecessary_const
    - unnecessary_new
    - unnecessary_null_in_if_null_operators
    - unnecessary_this
    - use_key_in_widget_constructors
    - use_rethrow_when_possible
