import 'package:spo_kick/features/bookings/domain/entities/booking_entity.dart';

import '../../domain/entities/booking_status.dart';

/// Booking data model (DTO) for JSON serialization.
///
/// Maps between database JSON and domain entity.
/// Optimized for Supabase PostgreSQL schema.
class BookingModel extends BookingEntity {
  const BookingModel({
    required super.id,
    required super.userId,
    required super.fieldId,
    required super.date,
    required super.startTime,
    required super.endTime,
    required super.status,
    required super.totalPrice,
    required super.currency,
    super.userName,
    super.fieldName,
    super.fieldImage,
    required super.createdAt,
    super.confirmedAt,
    super.canceledAt,
    super.cancellationReason,
    super.notes,
    super.isManual,
    super.createdBy,
    super.customerName,
    super.customerPhone,
    super.customerEmail,
  });

  /// Create model from JSON (from Supabase).
  ///
  /// Handles both simple bookings and enriched data with joins.
  factory BookingModel.fromJson(Map<String, dynamic> json) {
    return BookingModel(
      id: json['id'] as String,
      userId: json['user_id'] as String,
      fieldId: json['field_id'] as String,
      date: DateTime.parse(json['booking_date'] as String),
      startTime: json['start_time'] as String,
      endTime: json['end_time'] as String,
      status: (json['status'] as String).toBookingStatus(),
      totalPrice: (json['total_price'] as num).toDouble(),
      currency: json['currency'] as String? ?? 'EGP',
      // Optional fields from joins
      userName: json['user_name'] as String?,
      fieldName: json['field_name'] as String?,
      fieldImage: json['field_image'] as String?,
      // Timestamps
      createdAt: DateTime.parse(json['created_at'] as String),
      confirmedAt: json['confirmed_at'] != null
          ? DateTime.parse(json['confirmed_at'] as String)
          : null,
      canceledAt: json['canceled_at'] != null
          ? DateTime.parse(json['canceled_at'] as String)
          : null,
      cancellationReason: json['cancellation_reason'] as String?,
      notes: json['notes'] as String?,
      // Manual booking fields
      isManual: json['is_manual'] as bool? ?? false,
      createdBy: json['created_by'] as String?,
      customerName: json['customer_name'] as String?,
      customerPhone: json['customer_phone'] as String?,
      customerEmail: json['customer_email'] as String?,
    );
  }

  /// Convert model to JSON (for Supabase).
  ///
  /// Only includes fields needed for insert/update operations.
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'user_id': userId,
      'field_id': fieldId,
      'booking_date': date.toIso8601String().split('T')[0], // Date only
      'start_time': startTime,
      'end_time': endTime,
      'status': status.toShortString(),
      'total_price': totalPrice,
      'currency': currency,
      'notes': notes,
      'cancellation_reason': cancellationReason,
      'created_at': createdAt.toIso8601String(),
      if (confirmedAt != null) 'confirmed_at': confirmedAt!.toIso8601String(),
      if (canceledAt != null) 'canceled_at': canceledAt!.toIso8601String(),
      'is_manual': isManual,
      if (createdBy != null) 'created_by': createdBy,
      if (customerName != null) 'customer_name': customerName,
      if (customerPhone != null) 'customer_phone': customerPhone,
      if (customerEmail != null) 'customer_email': customerEmail,
    };
  }

  /// Create model for insert (without id and timestamps).
  ///
  /// Used when creating a new booking.
  Map<String, dynamic> toInsertJson() {
    return {
      'user_id': userId,
      'field_id': fieldId,
      'booking_date': date.toIso8601String().split('T')[0],
      'start_time': startTime,
      'end_time': endTime,
      'total_price': totalPrice,
      'currency': currency,
      if (notes != null && notes!.isNotEmpty) 'notes': notes,
      // Manual booking fields
      'is_manual': isManual,
      if (isManual)
        'status': 'confirmed', // Manual bookings are confirmed immediately
      if (createdBy != null) 'created_by': createdBy,
      if (customerName != null) 'customer_name': customerName,
      if (customerPhone != null) 'customer_phone': customerPhone,
      if (customerEmail != null && customerEmail!.isNotEmpty)
        'customer_email': customerEmail,
      // Don't include id, created_at (auto-generated by database)
      // For regular bookings, status defaults to 'pending'
    };
  }

  /// Create model for status update.
  ///
  /// Optimized for updating only status-related fields.
  Map<String, dynamic> toStatusUpdateJson() {
    return {
      'status': status.toShortString(),
      if (status == BookingStatus.canceled && cancellationReason != null)
        'cancellation_reason': cancellationReason,
    };
  }

  /// Convert from entity to model.
  factory BookingModel.fromEntity(BookingEntity entity) {
    return BookingModel(
      id: entity.id,
      userId: entity.userId,
      fieldId: entity.fieldId,
      date: entity.date,
      startTime: entity.startTime,
      endTime: entity.endTime,
      status: entity.status,
      totalPrice: entity.totalPrice,
      currency: entity.currency,
      userName: entity.userName,
      fieldName: entity.fieldName,
      fieldImage: entity.fieldImage,
      createdAt: entity.createdAt,
      confirmedAt: entity.confirmedAt,
      canceledAt: entity.canceledAt,
      cancellationReason: entity.cancellationReason,
      notes: entity.notes,
      isManual: entity.isManual,
      createdBy: entity.createdBy,
      customerName: entity.customerName,
      customerPhone: entity.customerPhone,
      customerEmail: entity.customerEmail,
    );
  }

  /// Convert model to entity.
  BookingEntity toEntity() {
    return BookingEntity(
      id: id,
      userId: userId,
      fieldId: fieldId,
      date: date,
      startTime: startTime,
      endTime: endTime,
      status: status,
      totalPrice: totalPrice,
      currency: currency,
      userName: userName,
      fieldName: fieldName,
      fieldImage: fieldImage,
      createdAt: createdAt,
      confirmedAt: confirmedAt,
      canceledAt: canceledAt,
      cancellationReason: cancellationReason,
      notes: notes,
      isManual: isManual,
      createdBy: createdBy,
      customerName: customerName,
      customerPhone: customerPhone,
      customerEmail: customerEmail,
    );
  }

  /// Create a copy with updated fields.
  @override
  BookingModel copyWith({
    String? id,
    String? userId,
    String? fieldId,
    DateTime? date,
    String? startTime,
    String? endTime,
    BookingStatus? status,
    double? totalPrice,
    String? currency,
    String? userName,
    String? fieldName,
    String? fieldImage,
    DateTime? createdAt,
    DateTime? confirmedAt,
    DateTime? canceledAt,
    String? cancellationReason,
    String? notes,
    bool? isManual,
    String? createdBy,
    String? customerName,
    String? customerPhone,
    String? customerEmail,
  }) {
    return BookingModel(
      id: id ?? this.id,
      userId: userId ?? this.userId,
      fieldId: fieldId ?? this.fieldId,
      date: date ?? this.date,
      startTime: startTime ?? this.startTime,
      endTime: endTime ?? this.endTime,
      status: status ?? this.status,
      totalPrice: totalPrice ?? this.totalPrice,
      currency: currency ?? this.currency,
      userName: userName ?? this.userName,
      fieldName: fieldName ?? this.fieldName,
      fieldImage: fieldImage ?? this.fieldImage,
      createdAt: createdAt ?? this.createdAt,
      confirmedAt: confirmedAt ?? this.confirmedAt,
      canceledAt: canceledAt ?? this.canceledAt,
      cancellationReason: cancellationReason ?? this.cancellationReason,
      notes: notes ?? this.notes,
      isManual: isManual ?? this.isManual,
      createdBy: createdBy ?? this.createdBy,
      customerName: customerName ?? this.customerName,
      customerPhone: customerPhone ?? this.customerPhone,
      customerEmail: customerEmail ?? this.customerEmail,
    );
  }
}
