// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtMR_RDMYXrzz-PDdg1C_zCKcc1J1MuuU',
    appId: '1:422156044280:web:7ac442964784792d68f80d',
    messagingSenderId: '422156044280',
    projectId: 'sport-kick',
    authDomain: 'sport-kick.firebaseapp.com',
    storageBucket: 'sport-kick.firebasestorage.app',
    measurementId: 'G-DG93Q56B73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaF_bX3ey-BrM6KHfUiuoUil4LXPDC88c',
    appId: '1:422156044280:android:66c2bbd035ccd0f868f80d',
    messagingSenderId: '422156044280',
    projectId: 'sport-kick',
    storageBucket: 'sport-kick.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa0Uoyy8wQwKDciPfHXYEy_cQ2LiN-bGA',
    appId: '1:422156044280:ios:e46f45110d8aa5b768f80d',
    messagingSenderId: '422156044280',
    projectId: 'sport-kick',
    storageBucket: 'sport-kick.firebasestorage.app',
    iosBundleId: 'com.example.spoKick',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtMR_RDMYXrzz-PDdg1C_zCKcc1J1MuuU',
    appId: '1:422156044280:web:cc59350dfd07380268f80d',
    messagingSenderId: '422156044280',
    projectId: 'sport-kick',
    authDomain: 'sport-kick.firebaseapp.com',
    storageBucket: 'sport-kick.firebasestorage.app',
    measurementId: 'G-XDRK7LH10V',
  );
}
