import 'package:dartz/dartz.dart';
import 'package:spo_kick/core/errors/exceptions.dart';
import 'package:spo_kick/core/errors/failures.dart';
import 'package:spo_kick/features/bookings/data/datasources/booking_remote_datasource.dart';
import 'package:spo_kick/features/bookings/data/models/booking_model.dart';
import 'package:spo_kick/features/bookings/domain/entities/booking_entity.dart';
import 'package:spo_kick/features/bookings/domain/entities/time_slot_entity.dart';
import 'package:spo_kick/features/bookings/domain/repositories/booking_repository.dart';

import '../../domain/entities/booking_status.dart';

/// Implementation of booking repository with caching and error handling.
///
/// Features:
/// - In-memory caching for frequently accessed data
/// - Automatic cache invalidation on mutations
/// - Proper exception to failure mapping
/// - Optimistic updates for better UX
class BookingRepositoryImpl implements BookingRepository {
  final BookingRemoteDataSource remoteDataSource;

  // Simple in-memory cache
  List<BookingEntity>? _cachedBookings;
  DateTime? _cacheTimestamp;

  // Cache duration (5 minutes)
  static const _cacheDuration = Duration(minutes: 5);

  BookingRepositoryImpl({required this.remoteDataSource});

  /// Check if cache is valid.
  bool get _isCacheValid {
    if (_cachedBookings == null || _cacheTimestamp == null) {
      return false;
    }

    final age = DateTime.now().difference(_cacheTimestamp!);
    return age < _cacheDuration;
  }

  /// Invalidate cache.
  void _invalidateCache() {
    _cachedBookings = null;
    _cacheTimestamp = null;
  }

  @override
  Future<Either<Failure, List<BookingEntity>>> getUserBookings() async {
    try {
      // Return cached data if valid
      if (_isCacheValid && _cachedBookings != null) {
        return Right(_cachedBookings!);
      }

      // Fetch from remote
      final bookings = await remoteDataSource.getUserBookings(
        // User ID is handled internally by data source
        '', // Placeholder, actual ID comes from auth
      );

      // Update cache
      _cachedBookings = bookings;
      _cacheTimestamp = DateTime.now();

      return Right(bookings);
    } on ServerException catch (e) {
      return Left(ServerFailure(e.message));
    } on AuthenticationException catch (e) {
      return Left(AuthenticationFailure(e.message));
    } on NetworkException catch (e) {
      return Left(NetworkFailure(e.message));
    } catch (e) {
      return Left(ServerFailure('Unexpected error: $e'));
    }
  }

  @override
  Future<Either<Failure, BookingEntity>> getBookingById(
    String bookingId,
  ) async {
    try {
      // Check cache first
      if (_isCacheValid && _cachedBookings != null) {
        try {
          final cached = _cachedBookings!.firstWhere((b) => b.id == bookingId);
          return Right(cached);
        } catch (_) {
          // Not in cache, proceed to remote
        }
      }

      // Fetch from remote
      final booking = await remoteDataSource.getBookingById(bookingId);

      return Right(booking);
    } on NotFoundException catch (e) {
      return Left(NotFoundFailure(e.message));
    } on ServerException catch (e) {
      return Left(ServerFailure(e.message));
    } on AuthenticationException catch (e) {
      return Left(AuthenticationFailure(e.message));
    } catch (e) {
      return Left(ServerFailure('Unexpected error: $e'));
    }
  }

  @override
  Future<Either<Failure, List<TimeSlotEntity>>> getAvailableTimeSlots({
    required String fieldId,
    required DateTime date,
  }) async {
    try {
      final timeSlots = await remoteDataSource.getAvailableTimeSlots(
        fieldId: fieldId,
        date: date,
      );

      return Right(timeSlots);
    } on NotFoundException catch (e) {
      return Left(NotFoundFailure(e.message));
    } on ServerException catch (e) {
      return Left(ServerFailure(e.message));
    } on NetworkException catch (e) {
      return Left(NetworkFailure(e.message));
    } catch (e) {
      return Left(ServerFailure('Unexpected error: $e'));
    }
  }

  @override
  Future<Either<Failure, BookingEntity>> createBooking({
    required String fieldId,
    required DateTime date,
    required String startTime,
    required String endTime,
    required double totalPrice,
    String? notes,
  }) async {
    try {
      // Create booking model
      final bookingModel = BookingModel(
        id: '', // Will be generated by database
        userId: '', // Will be set by data source from auth
        fieldId: fieldId,
        date: date,
        startTime: startTime,
        endTime: endTime,
        status: BookingStatus.pending,
        totalPrice: totalPrice,
        currency: 'EGP',
        notes: notes,
        createdAt: DateTime.now(),
      );

      // Create booking
      final booking = await remoteDataSource.createBooking(bookingModel);

      // Invalidate cache (new booking added)
      _invalidateCache();

      return Right(booking);
    } on ConflictException catch (e) {
      return Left(ConflictFailure(e.message));
    } on ValidationException catch (e) {
      return Left(ValidationFailure(e.message));
    } on ServerException catch (e) {
      return Left(ServerFailure(e.message));
    } on AuthenticationException catch (e) {
      return Left(AuthenticationFailure(e.message));
    } on NetworkException catch (e) {
      return Left(NetworkFailure(e.message));
    } catch (e) {
      return Left(ServerFailure('Unexpected error: $e'));
    }
  }

  @override
  Future<Either<Failure, BookingEntity>> cancelBooking({
    required String bookingId,
    required String reason,
  }) async {
    try {
      final booking = await remoteDataSource.cancelBooking(bookingId, reason);

      // Invalidate cache (booking status changed)
      _invalidateCache();

      return Right(booking);
    } on NotFoundException catch (e) {
      return Left(NotFoundFailure(e.message));
    } on ServerException catch (e) {
      return Left(ServerFailure(e.message));
    } on AuthenticationException catch (e) {
      return Left(AuthenticationFailure(e.message));
    } catch (e) {
      return Left(ServerFailure('Unexpected error: $e'));
    }
  }

  @override
  Future<Either<Failure, BookingEntity>> updateBookingStatus({
    required String bookingId,
    required BookingStatus status,
  }) async {
    try {
      final booking = await remoteDataSource.updateBookingStatus(
        bookingId,
        status,
      );

      // Invalidate cache (booking status changed)
      _invalidateCache();

      return Right(booking);
    } on NotFoundException catch (e) {
      return Left(NotFoundFailure(e.message));
    } on ServerException catch (e) {
      return Left(ServerFailure(e.message));
    } on AuthenticationException catch (e) {
      return Left(AuthenticationFailure(e.message));
    } catch (e) {
      return Left(ServerFailure('Unexpected error: $e'));
    }
  }

  @override
  Future<Either<Failure, List<BookingEntity>>> getBookingsByStatus({
    required BookingStatus status,
  }) async {
    try {
      final bookings = await remoteDataSource.getBookingsByStatus(
        '', // User ID handled by data source
        status,
      );

      return Right(bookings);
    } on ServerException catch (e) {
      return Left(ServerFailure(e.message));
    } on AuthenticationException catch (e) {
      return Left(AuthenticationFailure(e.message));
    } catch (e) {
      return Left(ServerFailure('Unexpected error: $e'));
    }
  }

  @override
  Future<Either<Failure, List<BookingEntity>>> getUpcomingBookings() async {
    try {
      // Get all bookings and filter client-side from cache if available
      final result = await getUserBookings();

      return result.fold((failure) => Left(failure), (bookings) {
        final upcoming = bookings
            .where((b) => b.status == BookingStatus.confirmed && !b.isPast)
            .toList();

        // Sort by date and time
        upcoming.sort((a, b) {
          final dateCompare = a.date.compareTo(b.date);
          if (dateCompare != 0) return dateCompare;
          return a.startTime.compareTo(b.startTime);
        });

        return Right(upcoming);
      });
    } catch (e) {
      return Left(ServerFailure('Unexpected error: $e'));
    }
  }

  @override
  Future<Either<Failure, List<BookingEntity>>> getBookingHistory() async {
    try {
      // Get all bookings and filter client-side
      final result = await getUserBookings();

      return result.fold((failure) => Left(failure), (bookings) {
        final history = bookings
            .where((b) => b.isPast || b.status == BookingStatus.canceled)
            .toList();

        // Sort by date (most recent first)
        history.sort((a, b) => b.date.compareTo(a.date));

        return Right(history);
      });
    } catch (e) {
      return Left(ServerFailure('Unexpected error: $e'));
    }
  }

  @override
  Future<Either<Failure, List<BookingEntity>>> getOwnerBookings() async {
    try {
      // Fetch bookings for fields owned by current user
      final bookings = await remoteDataSource.getOwnerBookings();

      return Right(bookings);
    } on ServerException catch (e) {
      return Left(ServerFailure(e.message));
    } on AuthenticationException catch (e) {
      return Left(AuthenticationFailure(e.message));
    } on NetworkException catch (e) {
      return Left(NetworkFailure(e.message));
    } catch (e) {
      return Left(ServerFailure('Unexpected error: $e'));
    }
  }

  @override
  Future<Either<Failure, List<BookingEntity>>> getAllBookings() async {
    try {
      // Fetch all bookings in the system (for super admin only)
      final bookings = await remoteDataSource.getAllBookings();

      return Right(bookings);
    } on ServerException catch (e) {
      return Left(ServerFailure(e.message));
    } on AuthenticationException catch (e) {
      return Left(AuthenticationFailure(e.message));
    } on NetworkException catch (e) {
      return Left(NetworkFailure(e.message));
    } catch (e) {
      return Left(ServerFailure('Unexpected error: $e'));
    }
  }

  @override
  Future<Either<Failure, BookingEntity>> createManualBooking({
    required String fieldId,
    required DateTime date,
    required String startTime,
    required String endTime,
    required double totalPrice,
    required String customerName,
    required String customerPhone,
    String? customerEmail,
    String? notes,
  }) async {
    try {
      // Create booking model with manual booking flag
      final booking = BookingModel(
        id: '', // Will be generated by database
        userId: '', // Will be set by datasource to current admin ID
        fieldId: fieldId,
        date: date,
        startTime: startTime,
        endTime: endTime,
        status: BookingStatus.confirmed, // Manual bookings are auto-confirmed
        totalPrice: totalPrice,
        currency: 'EGP',
        createdAt: DateTime.now(),
        isManual: true,
        customerName: customerName,
        customerPhone: customerPhone,
        customerEmail: customerEmail,
        notes: notes,
      );

      final createdBooking = await remoteDataSource.createManualBooking(
        booking,
      );

      // Invalidate cache (new booking created)
      _invalidateCache();

      return Right(createdBooking);
    } on ConflictException catch (e) {
      return Left(ConflictFailure(e.message));
    } on ValidationException catch (e) {
      return Left(ValidationFailure(e.message));
    } on ServerException catch (e) {
      return Left(ServerFailure(e.message));
    } on AuthenticationException catch (e) {
      return Left(AuthenticationFailure(e.message));
    } catch (e) {
      return Left(ServerFailure('Unexpected error: $e'));
    }
  }

  /// Clear cache (for testing or manual refresh).
  void clearCache() {
    _invalidateCache();
  }
}
